# Generated by Django 3.0.2 on 2020-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0008_auto_20200213_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name1', models.CharField(max_length=300, verbose_name='Name of Eevnt')),
                ('p_loc1', models.CharField(max_length=300, verbose_name='Location')),
                ('p_det1', models.TextField(blank=True, verbose_name='Additional Details')),
                ('p_high1', models.TextField(blank=True, verbose_name='Highlights')),
                ('p_price1', models.TextField(blank=True, verbose_name='Date')),
                ('p_app1', models.BooleanField(default=False, null=True, verbose_name='Approval')),
                ('p_img1', models.FileField(upload_to='media/', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
