# Generated by Django 3.0.2 on 2020-05-18 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0009_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pckimg',
            options={'verbose_name': 'Event Image', 'verbose_name_plural': 'Event Images'},
        ),
        migrations.AlterModelOptions(
            name='sgts',
            options={'verbose_name': 'Community Name', 'verbose_name_plural': 'Funds raised'},
        ),
        migrations.AlterField(
            model_name='events',
            name='p_price1',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='pckimg',
            name='p_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyse.events', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='sgts',
            name='s_url',
            field=models.CharField(max_length=300, verbose_name='Funds'),
        ),
    ]
